name: Bug Report
description: Bug Report
labels:
  - Bug
title: "[Bug Report] Your bug report title here"
body:
  - type: textarea
    attributes:
      label: Describe the problem
      description: Please provide a concise description of what you are experiencing.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected behavior
      description: Please provide a concise description of what you expect to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: false
  - type: input
    id: firebotMagePlatformLib_version
    attributes:
      label: Mage Platform Library Version
      description: What version of Mage Platform Library are you running?
    validations:
      required: true
  - type: input
    id: firebotIntegration_version
    attributes:
      label: Firebot Kick/YouTube Integration Version
      description: What version(s) of Firebot Kick/YouTube Integration are you running?
    validations:
      required: true
  - type: input
    id: firebot_version
    attributes:
      label: Firebot Version
      description: What version of Firebot are you running?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Please provide any additional information that you think may be helpful.
    validations:
      required: false
